# Generated by Django 5.0.6 on 2024-05-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_customer_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
